apiVersion: apps/v1
kind: Deployment
metadata:
 labels:
  app: httpd
 name: httpd
 namespace: advanced
spec:
 replicas: 1
 selector:
  matchLabels:
   app: httpd
 template:
  metadata:
   labels:
     app: httpd
  spec:
   containers:
   #- image: repo.rhbroker.com/prd/httpd:2.4
   - image: 192.168.2.10:5000/myweb:2
     name: httpd
     imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: httpd
  namespace: advanced
spec:
  type: NodePort
  ports:
   - port: 8040
     targetPort: 80
     nodePort: 32123
  selector:
    app: httpd
